version: '3.8'

services:
  agent-swarm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentswarm_app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-3.5-turbo}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}
      - VECTOR_STORE_PATH=/app/data/vector_store
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
    volumes:
      - vector_data:/app/data/vector_store
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  vector_data: