version: '3.8'

services:
  agent-swarm:
    build: .
    container_name: agentswarm_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=gpt-3.5-turbo
      - LLM_TEMPERATURE=0.7
      - VECTOR_STORE_PATH=/app/data/vector_store
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    volumes:
      - vector_data:/app/data/vector_store
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  vector_data: